### ISSUE TITLE
Add network inspection tool

### ISSUE THREAD

**Issue by S-S-X** [mt-mods/technic#107]
### Background
I made simple debug hud that displays information for pointed node revealing useful network information, for debugging it has been just network id and location with some supply converter metadata when looking at supply converters.
That was really useful tool during network development as it did reveal problems and also in some case guided finding better ways to handle things.

### Proposal
So proposing something similar to network debug hud but as craftable tool so **:zap: everyone can be real power grid engineer :zap:**
Tool should give technical internal information about network in game.

Some useful information tool could return:
* network id for node, preferably encoded to be more readable.
* switching station locations.
* network input / output values.
* all_nodes count.
* machine count by type.
* cable count.
* network ttl value, absolute and remaining.
* total battery capacity.
* total battery charge.

Should wait until #96 is done.

**Comment by S-S-X** [comment]
Preview for network inspection tool pushed to [multimeter](https://github.com/mt-mods/technic/tree/multimeter) branch.
Feel free to test and comment on it.
Tool has basic functionality and expensive recipe... displays most of data listed in issue description.

**Comment by OgelGames** [comment]
Don't really think it should or needs to be branded (also could cause some confusion for those who don't know the Fluke brand), but it looks good otherwise, I'll give it a test later 👍

**Comment by S-S-X** [comment]
Also a lot simpler and cheaper recipe and removed bad `mesecons_material` dependency (not in technic hard dependencies).

But now that I added remote network start function, while it uses 100x charge (max 4 remote starts) compared to normal read and network TTL 5 minutes (default is 30 minutes) it still does make tool a lot more powerful so maybe more expensive recipe could be fine.

Remote started networks do not get any special benefits in globalstep run and might be disabled right away in case time usage is too high. Pretty sure there is no way to automate remote starts easily (at least not easier than jumping around to activate networks for long ttl).

**Comment by OgelGames** [comment]
So I tested it, and I have a few suggestions:

- Get rid of the "FLUTE" branding, because it will almost certainly cause confusion with the musical instrument, and it's unnecessary.
- Change `Value 1` and `Value 2` to `Value` and `Unit`, leaving the unit blank for some of the properties, such as active state.
- Add a description for each of the properties that is shown when it is selected.
- Add a "Clear Waypoints" button, and remove the exit button.
- Set the formspec background to a solid color (it's almost like that anyway).

Also I didn't think the inventory/wield image looked very good, so I quickly made this: 😄 
![technic_multimeter](https://user-images.githubusercontent.com/48543043/97848611-6fc40b80-1d45-11eb-9333-0ad0fecd3325.png)

**Comment by BuckarooBanzay** [comment]
> Get rid of the "FLUTE" branding, because it will almost certainly cause confusion with the musical instrument, and it's unnecessary.

I kinda love the name (Not a fluke fan but i love the name-play)

@OgelGames your wield image does look better IMO

**Comment by OgelGames** [comment]
> I kinda love the name (Not a fluke fan but i love the name-play)

To be honest I actually like it too, maybe it could be just removed from the name, and still be in the formspec...
