### ISSUE TITLE
Iron chest recipe has vanished

### ISSUE THREAD

**Issue by SwissalpS** [mt-mods/technic#127]

**Comment by S-S-X** [comment]
Tested also with fewer mods and got same results recipe is not just missing from guide but it is really missing, there's no  recipe available to craft iron chest.

**Comment by BuckarooBanzay** [comment]
works for me locally with 16d36c63cc7ff8bdb0f1d4279ec43ae94fc82e46 :thinking:

recipe register call:
https://github.com/mt-mods/technic/blob/16d36c63cc7ff8bdb0f1d4279ec43ae94fc82e46/technic_chests/chests.lua#L77-L83

recipe registering:
https://github.com/mt-mods/technic/blob/16d36c63cc7ff8bdb0f1d4279ec43ae94fc82e46/technic_chests/chests.lua#L18-L25

let me check the test server...

**Comment by BuckarooBanzay** [comment]
found the issue:

The check here fails for `technic:cast_iron_ingot`:
https://github.com/mt-mods/technic/blob/16d36c63cc7ff8bdb0f1d4279ec43ae94fc82e46/technic_chests/chests.lua#L16

because `technic` is loaded _after_ the `technic_chests` mod :yum: 
https://github.com/mt-mods/technic/blob/16d36c63cc7ff8bdb0f1d4279ec43ae94fc82e46/technic_chests/mod.conf#L1-L3

my suggestion would be to drop the redundant `if minetest.registered_items[material] then` check

**Comment by S-S-X** [comment]
> because technic is loaded after the technic_chests mod

@BuckarooBanzay should probably also add technic as optional dependency for chests

**Comment by BuckarooBanzay** [comment]
> @BuckarooBanzay should probably also add technic as optional dependency for chests

Hmm, did not test that, looks like `technic` has no dependency on `technic_chests` i just assumed it had :confounded:

**Comment by OgelGames** [comment]
Fixed by adding optional dependency on `technic_worldgen`.

Also, because `technic_chests` needs to be loaded after `technic` because it uses the `technic` namespace, I added that as a optional dependency too.
