### ISSUE TITLE
HV cable digiline support

### ISSUE THREAD

**Issue by thomasrudin** [mt-mods/technic#14]
* ~~check digilines remote mod (performance)~~
* ~~alternative: lightweight roll-your-own-remote with digiline rules~~

* [x] New HV cable with `digiline` field definition (like digimese)
* [x] HV Reactor: proper digiline interface
* [x] Performance testing with huge networks

**Comment by tuedel** [comment]
What about adding (HV) power cables with digiline connectivity? I never liked the idea of having to use a "remote control" in the first place... :wink:

**Comment by thomasrudin** [comment]
Oh, thats even better, i think this just needs the `digiline` field in the HV-Cable definition, like the `digimese` block from digistuff:

```lua
minetest.register_node("digistuff:digimese", {
        description = "Digimese",
        tiles = {"digistuff_digimese.png"},
        paramtype = "light",
        light_source = 3,
        groups = {cracky = 3, level = 2},
        is_ground_content = false,
        sounds = default and default.node_sound_stone_defaults(),
        digiline = { wire = { rules = {
        {x = 1, y = 0, z = 0},
        {x =-1, y = 0, z = 0},
        {x = 0, y = 1, z = 0},
        {x = 0, y =-1, z = 0},
        {x = 0, y = 0, z = 1},
        {x = 0, y = 0, z =-1}}}}
})
```

But then again, the reactor does not have (yet) a proper digiline interface:

https://github.com/pandorabox-io/technic/blob/master/technic/machines/HV/nuclear_reactor.lua#L397

(just the digiline_remote thing)

**Comment by S-S-X** [comment]
Opinion here:

I would like digiline HV cables a lot, would solve many problems.

Just make sure to add another node for digiline HV cables, maybe some digilines + HV cable, or digimese + HV cable if it conducts exactly like digimese.

If current cables will just simply get digiline support that will create big issues in many machines and I do also think that especially if it conducts like digimese then it should have digimese for recipe too (or at least 8 digilines).

**Comment by S-S-X** [comment]
I tested simple digicables registration, will commit proposal to some branch soon.

![screenshot_20200421_210303](https://user-images.githubusercontent.com/50966843/79898667-50ead100-8414-11ea-89cb-546a09260df3.png)
![screenshot_20200421_210750](https://user-images.githubusercontent.com/50966843/79898699-5e07c000-8414-11ea-8f1d-7882bb051c4d.png)

**Comment by BuckarooBanzay** [comment]
Oh :astonished: nice, did you notice anything performance-related yet?

**Comment by S-S-X** [comment]
> Oh astonished nice, did you notice anything performance-related yet?

Didnt really test at all but this should not affect performance at all.
Networks look for next cable from hash table and this adds few nodes to that table, therefore lookup should be very fast.

I think that is only addition that really can affect performance.

**Comment by S-S-X** [comment]
I think current recipe is too cheap as it basically switches mese block to HV cable which requires non renewable resources 0,33 coal lump and 0,25 copper lump / cable vs mese block / digimese, this should not encourage using HV cables in place of digimese blocks.

Should it be simply recipe to combine digimese + HV cable = HV digi cable?

**Comment by BuckarooBanzay** [comment]
> Should it be simply recipe to combine digimese + HV cable = HV digi cable?

This sounds balanced :+1: (i did prefer the previous recipe but i already see players using hv-cables instead of digimese blocks in my head...)

I see if i can spare some time for testing, this will be awesome...

**Comment by S-S-X** [comment]
recipe updated + added checks if required mods are enabled and updated dependencies.

**Comment by BuckarooBanzay** [comment]
rewrote the `digilines_remote` interface to plain `digilines`, everything else should be addressed.
closing this, thanks @S-S-X :tada:

**Comment by tuedel** [comment]
@S-S-X  Thanks a lot for implementing this :+1: 

> I think current recipe is too cheap as it basically switches mese block to HV cable which requires non renewable resources 0,33 coal lump and 0,25 copper lump / cable vs mese block / digimese, this should not encourage using HV cables in place of digimese blocks.
> 
> Should it be simply recipe to combine digimese + HV cable = HV digi cable?

IMO the recipe with digimese (like digimese itself) is a bit too expensive, using a whole block of mese for a cable which doesn't even conduct mese signals doesn't seem justified.

Take a look at the "junction box" from digistuff (https://cheapiesystems.com/git/digistuff/tree/conductors.lua#n75). It is way cheaper than digimese (4 plastic sheet/5 digiline wire) and offers more possible connections (2 nodes in every direction), so the availability of HV digiline cable alone doesn't really "devalue" digimese in any way.

I think first recipe (1 HV cable/8 digiline wire) was perfectly fine.

**Comment by S-S-X** [comment]
@tuedel I do agree with most of what you just said

> the recipe with digimese (like digimese itself) is a bit too expensive

I do too think that it is a bit too expensive but it was closest option while keeping it simple.

> Take a look at the "junction box" from digistuff (https://cheapiesystems.com/git/digistuff/tree/conductors.lua#n75). It is way cheaper than digimese (4 plastic sheet/5 digiline wire) and offers more possible connections

For this I do not think this is good argument in any other way than pointing out that there's game balance problem in digistuff mod. That's because I think that we should not make new stuff poorly balanced just because other stuff is also poorly balanced.

However at the same time that point kind of makes sense as after all it is really hard to make everything balanced when stuff comes from sources that do not really cooperate that well, care about different things, are maintained by different people and there's no really so deep quality testing (if any) that could ever catch all of these problems until someone discovers it and points out that there is problem. But then, this is something that can be fixed even while it for sure will take a long time.

> I think first recipe (1 HV cable/8 digiline wire) was perfectly fine.

I do also think that it would be a lot nicer but also that it _might_ have problems with balancing things.
There's that recipe already available, I left it there because without digistuff it is for sure better recipe:
https://github.com/mt-mods/technic/blob/master/technic/machines/HV/cables.lua#L16-L31

Maybe also make that bit configurable as that would be fairly easy, so it could be used even if digistuff is available?

I'm not sure currently what would be best thing to do but I would like to at least attempt to balance things when changes are made.
Why I first started thinking that recipe cheaper than digimese isnt good thing was simple fact that combined HV cable+digimese is so powerful (an not passive component when in contact with network) that it for sure should be at least a bit more expensive than just digimese.

Any other opinions / thoughts would be welcome?
