### ISSUE TITLE
Combine `concrete` mod into `technic` and `extranodes` mods

### ISSUE THREAD

**Issue by OgelGames** [mt-mods/technic#144]
Blast-resistant concrete is required by the HV nuclear reactor for it to function, so that should be part of the `technic` mod, the other various concrete nodes are not used by anything, so they are suitable for the `extranodes` mod.

**Comment by S-S-X** [comment]
I don't really see any issues in mod structure, only that concrete is not optional dependency for technic and before registering nuclear reactor it does not check if BRC is available.

In my opinion it would be better to keep building blocks in separate mod like how those currently are and fix dependencies.

**Comment by OgelGames** [comment]
> not moving those will keep hacks like more aliases (or registration for foreign mod name) out

The nodes are already registered under the `technic` mod name:

https://github.com/mt-mods/technic/blob/c17c2e543cde2187bb892856489130e3b455ccc6/concrete/init.lua#L44
https://github.com/mt-mods/technic/blob/c17c2e543cde2187bb892856489130e3b455ccc6/concrete/init.lua#L79

**Comment by S-S-X** [comment]
> The nodes are already registered under the technic mod name:

Yeah now it makes a lot more sense to scrap concrete and combine into technic mod.
Maybe first just remove concrete and move everything into technic by just simply moving directory and adding required dofile lines to init.

Seems like situation is bit more complicated and cannot be really fixed well without either adding aliases or keeping foreign mod name in register calls... because BRC is still building block that can be used without technic mod and not just ingredient for some technic machine.

**Comment by OgelGames** [comment]
> if you'd like to use just BRC building block without all other technic stuff

Maybe `technic_worldgen` is a better place for BRC? `technic` already depends on that...

**Comment by S-S-X** [comment]
For me technic_worldgen sounds best candidate so far, it also registers other things needed for both machines (ingots/blocks used in crafting) and nuclear reactor (lead blocks).

Sounds like good idea to have both concrete and blast resistant concrete registered there too, blocks required to actually build nuclear reactor would also live under single mod.
