### ISSUE TITLE
ERROR[Main]: generateImage(): Could not load image

### ISSUE THREAD

**Issue by AmyMoriyama** [mt-mods/technic#196]
2021-07-12 17:12:24: ERROR[Main]: generateImage(): Could not load image "technic_concrete_block.png" while building texture; Creating a dummy image

2021-07-12 17:12:24: ERROR[Main]: generateImage(): Could not load image "technic_concrete_block.png" while building texture; Creating a dummy image

**Comment by OgelGames** [comment]
I noticed you also posted this here: https://github.com/minetest-mods/technic/issues/589

Which version of technic are you running, and when is this error happening?

**Comment by S-S-X** [comment]
Commit https://github.com/mt-mods/technic/commit/bc51bca63cc807e9068c8717ed0730d2399f21f7 moved concrete/textures/x32/technic_concrete_block.png → .textures/alternate/technic_concrete_block.png

For me however it seems that technic mod does not use this texture for anything.
Issue is in another outdated mod and issue became only visible because technic_concrete_block.png texture were basically removed from technic mod.

Technic mod did throw away concrete block textures here: https://github.com/mt-mods/technic/commit/44cb8df048e09b64214f59db73a3fd23cfe12e77 (november 2018).

At this point my opinion is that this is not bug _(and I'll remove bug label for now)_ and should not be fixed by restoring unused texture, another mod that is trying to use this texture should be fixed instead. Basic_materials mod provides correct textures.

Texture .textures/alternate/technic_concrete_block.png should be removed completely to keep it clean and to avoid possible confusion.
