### ISSUE TITLE
Radiation damage don't work?

### ISSUE THREAD

**Issue by zbx-pandorabox** [mt-mods/technic#29]
Hi, If I use this fork, radiation damage don't work(on pandorabox don't work too).

**Comment by BuckarooBanzay** [comment]
This may be cause by a recent commit:
https://github.com/mt-mods/technic/commit/8a7563c0964515c6d091938ca8b6eb2f0b6bdbba#diff-60fee4b2341ad5bd5e4577b217ed1c8d

This skips all radiation calculations if the average lag is above 1.5 seconds.
Radiation calculation is pretty cpu-intensive due to various raycasting calls...

Can you retest that in singleplayer and wait a few seconds/minutes until the avg_lag reported by `/status` is lower than 1.5 seconds...?

**Comment by zbx-pandorabox** [comment]
Tested in singleplayer game with lag under 1 sec, no rad dmg(if I disable radioactive gas mod, maybe I can get sometimes a little dmg from uranium ore but hardly ever. I don't test this deeply, I'm not sure). If I switch to minetest-mods/technic mod, rad dmg working as usual.

**Comment by BuckarooBanzay** [comment]
did you by any chance disable `damage` in the settings? This would explain it...

**Comment by zbx-pandorabox** [comment]
I changed test for max_lag in radiation.lua from 1.5 to 10 and rad dmg working as usual. Thx for your advice.
(I'm sry for my hasty comment above, there has been some anomaly/my mistake on my computer, I don't have now lag under 1sec.).

**Comment by BuckarooBanzay** [comment]
good to hear :+1: , closing this. Feel free to re-open if it persists...
