### ISSUE TITLE
[Bug] Grinding nuggets gives two dust (MCL)

### ISSUE THREAD

**Issue by ThePython10110** [mt-mods/technic#341]
In MineClone2 (and therefore probably Mineclonia), you can grind a gold or iron nugget to get two dust. Since a nugget is 1/9 of an ingot, it should take at least 9 nuggets to make 1 dust.

**Comment by BuckarooBanzay** [comment]
The original idea (from the `default` game) was to provide a better way to process lumps to ingots with two times the yield.

* "normal" smelting process: 1 lump -> 1 ingot
* grinding process: 1 lump -> 2 dust -> 2 ingots

> Since a nugget is 1/9 of an ingot, it should take at least 9 nuggets to make 1 dust.

Sounds good, but i don't think the input material-count can be specified in the recipes :thinking: 

## Relevant code sections

Grinder recipes:
https://github.com/mt-mods/technic/blob/da0378aead4c596526cc2955c139929087626c13/technic/machines/register/grinder_recipes.lua#L16-L22
(mcl recipes might have to add a recipe-switch here ^ directly instead of using the material 1:1)

Game/Material switch:
https://github.com/mt-mods/technic/blob/da0378aead4c596526cc2955c139929087626c13/technic/materials.lua#L11-L14

**Comment by S-S-X** [comment]
> Sounds good, but i don't think the input material-count can be specified in the recipes 🤔

Everything for base machines should be able to handle item count in input, alloy recipes have examples for this.

So just making it 9 in 1 out should work.

**Comment by programmerjake** [comment]
imo the proper fix is to have the grinder be able to grind ore blocks and raw ores since those are analogous to ore lumps in minetest game, not nuggets.

**Comment by programmerjake** [comment]
@nonfreegithub what do you think, since you wrote the mineclone compatibility PR?
