### ISSUE TITLE
enhancing chests

### ISSUE THREAD

**Issue by wsor4035** [mt-mods/technic#73]
it would be nice to see https://github.com/GreenXenith/technic_chests features added here, sorting, items to and from chest to inv is invaluable for big material moves

**Comment by BuckarooBanzay** [comment]
The features are nice, but it looks like a lot of work untangling his commits and applying it to the current codebase :confounded:

**Comment by OgelGames** [comment]
Thought I should let you know what I've been doing since I assigned this to myself, I decided to go further than just adding the features mentioned above, and ended up with a lot more to do than I thought I would...

As of right now, these are the things I'm changing/adding:
- Adding multiple ways to move items between the chest and the player's inventory.
- Adding additional sorting modes (so far only added sorting by quantity).
- Adding digilines functionality (mostly to do with querying what is inside the chest).
- Reorganizing the formspecs to look better and use space more efficiently.
- Completely rewriting the code to be simpler, easier to read, and more flexible for possible future additions.

Not finished or ready for testing yet, but here's a preview of what it will look like 😉 

![screenshot_20201024_211257](https://user-images.githubusercontent.com/48543043/97079254-220d1c00-163e-11eb-90d5-906ceb4d0bc4.png)

@SwissalpS @jessicara @S-S-X @6r1d

**Comment by wsor4035** [comment]
quote from discord
> will it still have Support for the area mod?

**Comment by S-S-X** [comment]
@wsor4035 
> quote from discord
> 
> > will it still have Support for the area mod?

Not sure what that means but if it is question for mithril chest protection then yes, it is not mod dependent feature but instead uses `minetest.is_protected` and protection mods should override that to implement protection checks.

@OgelGames 
> Not finished or ready for testing yet, but here's a preview of what it will look like

Will there be way to disable/hide all advanced features? I think there might be some use for that, possibly even with server wide configuration option for default value. Could be single button/checkbox that toggles all advanced features in formspec and disables/enables all code handling advanced stuff for that specific chest,

Also will there be color picker or will it be removed? If it will be removed how chests that do have selected color will be handled?
Interesting thing would be to have digiline api for changing color :smile: 

Look very good replacement for vendors and I will for sure find many uses for chests like this very soon :+1:

**Comment by OgelGames** [comment]
> quote from discord
> 
> > will it still have Support for the area mod?

Yes, in fact there will probably be more support because I'm thinking of having protected versions of all the chests.

> Will there be way to disable/hide all advanced features?

I don't think that is necessary, it just adds more complexity, and I don't like hiding things.

> Also will there be color picker or will it be removed?

No, that will stay exclusive to the gold chest, and mithril chest will swap it out for digilines.

> very good replacement for vendors

Well that was my plan, to make them better than vendors 😉

**Comment by wsor4035** [comment]
they where referring to the ability from greenxeniths chests to check a box to allow people in your area to access the chest or not

**Comment by OgelGames** [comment]
> .. the ability ... to check a box to allow people in your area to access the chest or not ...

I decided to not add that feature because we already have the mithril protected chest, and I think it is also clearer having a different type of chest, just like locked chests. Also it is consistent with the wooden chests, which have open, locked, and protected versions.

**Comment by SwissalpS** [comment]
I too am looking forward to replacing some vendors :)

One other thing I like about fancy vendors is the wand. I would already like to have a wand for normal chests and technic machines to set the 'split incomming' and 'autosort' toggles. With more complex toggles, this wish will become even stronger.

**Comment by wsor4035** [comment]
OgelGames: so anyone on the area that has a protected chest can access it?

**Comment by OgelGames** [comment]
> One other thing I like about fancy vendors is the wand. I would already like to have a wand for normal chests and technic machines to set the 'split incomming' and 'autosort' toggles. With more complex toggles, this wish will become even stronger.

Not sure about adding yet another copying tool, but maybe if it was some multipurpose "Technic Configurator" tool, then maybe it would be a good idea... :thinking:

> OgelGames: so anyone on the area that has a protected chest can access it?

Exactly 👍

**Comment by S-S-X** [comment]
> Not sure about adding yet another copying tool

Could add this for metatool as it is designed exactly for these things, copying / modifying internal data. Thing is metatool are not for single mod but designed to be general tool that can support other things with similar parameters and move data between those.

**Comment by SwissalpS** [comment]
Fancy Vendor is also a secret chest that only shows content to owner and managers.

**Comment by mase76** [comment]
Why digilines for mithril chests only? That makes a big automated storage impossibly expensive.

**Comment by SwissalpS** [comment]
Big storage requires big chests and big income :D
It's also good to have tiers.
Players who can afford it, get more functions. Adding some functions to lower tiered chests would devalue the higher tiers.
Also the colour lends well to the added functionality. :D
