### ISSUE TITLE
Use nodetimers on switching station

### ISSUE THREAD

**Issue by BuckarooBanzay** [mt-mods/technic#75]

**Comment by S-S-X** [comment]
After this is done `technic.switch.off_delay_seconds` does not have meaningful use anymore and switching wont stay active after after area becomes inactive? Or after area becomes unloaded?

Anyway, as nodetimers wont keep running always which is good but good to clean up things that wont be available because of this.
Maybe it could also be possible to offer both ways through configuration but probably not worth it, after switching to nodetimers it is either anchor or inactive.

**Comment by BuckarooBanzay** [comment]
> After this is done technic.switch.off_delay_seconds does not have meaningful use anymore and switching wont stay active after after area becomes inactive? Or after area becomes unloaded?

The (current) switching station abm just updates the global index of switching-stations with the last time it was updated/loaded/active:

https://github.com/mt-mods/technic/blob/d1efc4bdd93fc386b69264dde8d7176b78fe0682/technic/machines/switching_station_globalstep.lua#L35-L45

The global index:

https://github.com/mt-mods/technic/blob/d1efc4bdd93fc386b69264dde8d7176b78fe0682/technic/machines/switching_station_globalstep.lua#L4-L19

The actual `technic_run()` is still called when the area is left alone until the amount of seconds in `technic.switch_off_delay` is reached:

https://github.com/mt-mods/technic/blob/d1efc4bdd93fc386b69264dde8d7176b78fe0682/technic/machines/switching_station_globalstep.lua#L100

If the timeout is reached then the switching station gets removed from the index:

https://github.com/mt-mods/technic/blob/d1efc4bdd93fc386b69264dde8d7176b78fe0682/technic/machines/switching_station_globalstep.lua#L138-L139

(i should really document this somewhere, maybe some kind of "internals" readme...)

**Comment by S-S-X** [comment]
I was actually thinking this was going to actually replace also globalstep with nodetimers, if not then of course switching just those ABM's to nodetimers wont affect `technic.switch.off_delay_seconds`

**Comment by S-S-X** [comment]
This one should be much simpler change now as no special checks for other switching stations are needed at all, should be able to simply throw ABM away and add node timers.

After #96 got merged ABM is just blindly activating network and updating its own infotext:
https://github.com/mt-mods/technic/blob/c89d0a1305ff6d0d07e153f92b008d86149f24a0/technic/machines/switching_station.lua#L139-L170

**Comment by BuckarooBanzay** [comment]
Hmm, that might not be so simple after all, the nodetimer has to be kicked off initially somewhere :thinking: 
That usually happens in an `after_place` callback or something like that (which isn't the case in already placed switches).

Another thing i've heard is that nodetimers sometimes don't fire anymore (@Warr1024 can you confirm that, i think we talked about that on discord)

Which would mean that there should be an lbm too which "migrates" to the nodetimer refresher or re-initializes the timer :shrug:

**Comment by S-S-X** [comment]
> Hmm, that might not be so simple after all, the nodetimer has to be kicked off initially somewhere

#109 can be used for that.

> Another thing i've heard is that nodetimers sometimes don't fire anymore

This is big problem and show stopper if nodetimers might just stop  working without any real reason, these timers must be reliable because there's nothing that would restart those timers and fixing would require player to somehow know that switching station must be removed and placed again.
Not good also because you really can not easily determine which switching stations have lost their timers.

So first problem can be sorted out but second one, if real, is show stopper if nodetimers are not reliable. It does not really make sense to add another ABM or LBM to start failed nodetimers...

**Comment by BuckarooBanzay** [comment]
> So first problem can be sorted out but second one, if real, is show stopper if nodetimers are not reliable. It does not really make sense to add another ABM or LBM to start failed nodetimers...

The nodetimer issue may be not a problem (anymore?) because as far as i know i haven't seen the particle-fountain at spawn acting up and that node is working with a node-timer :smile:
