### ISSUE TITLE
power monitor "has no network"

### ISSUE THREAD

**Issue by BuckarooBanzay** [mt-mods/technic#76]
@S-S-X looks like your recent commit 7c45e88d0695a72095b55d95a00a069b8e7848fb has had some impact on the power monitors:

![screenshot_20200903_212135](https://user-images.githubusercontent.com/39065740/92158031-963ff600-ee2b-11ea-9cd9-40426b286dd9.png)

I tried a few constellations but in most of them the monitor has no network.

I see if i have some time to investigate the next few days, no idea yet what the cause would be..

**Comment by S-S-X** [comment]
Oh yes, actually I did look around some days ago when Huhhila told me that those are not working at all.
It is most probably network id change, it was messy but after power monitor code has been updated it is less messy.
There was unnecessarily multiple ways to identify network and I did drop one when I thought it was not used anywhere but I believe it might be cause for power monitors not working.

**Comment by S-S-X** [comment]
Checked situation a bit and network id is kinda fine, actually power monitor did not use data I removed.
Root cause seems to actually be number `tostring` conversion. Tested and verified that network id seems to be some nodes off because of that, if switch built to actual network id hash location then it works. If `tostring` eliminated, then it also works but at any coords without messing up numbers.

**Comment by S-S-X** [comment]
That commit should already fix power monitors, @BuckarooBanzay interested testing it?
Biggest change is that metadata is not used for network id storage, instead uses already existing in memory tables. Should simplify internal network data storage significantly as there's one less place to take care of when updating data.

**Comment by BuckarooBanzay** [comment]
> That commit should already fix power monitors, @BuckarooBanzay interested testing it?
> Biggest change is that metadata is not used for network id storage, instead uses already existing in memory tables. Should simplify internal network data storage significantly as there's one less place to take care of when updating data.

Tested it locally, looks good so far, the monitors have all the data now and the rest seems to work :+1:

**Comment by S-S-X** [comment]
Found some extra time again to check this technic stuff and now I think that power monitor does not actually have to be part of actual technic network, it could as well be standalone thing that would simply read switching station supply/demand.

This is actually what it does currently but what I mean it does not have to go through all other checks / power consumption (which is 0 but it is still consumer). There's also comment about that in power monitor source file.

It does use ABM that executes every second, it checks network it belongs to and uses network data to find switching station and simply reads supply and demand to display those.

What it could do instead of being registered as technic machine:
* Everything it does currently: determine network it belongs to, find switching station, read data, display data.
* Instead of actually being part of actual network it could simply get network id from connected cable.

What is required to make it work like this, I see two options:

1. Least complicated: ABM execution checks cable below or behind it (based on allowed connections) and reads network id from there. I think this should work without problems but it would have to also check if connected cable still belongs to network (cheap and easy check).
2. More complicated: Have special machine class that wont get attached to actual network and does not have cache entry but still gets network data updated when actual network is updated (caches built).

That way power monitor could be standalone machine that does not actually belong to network under the hood even while in game it looks like it does belong to network.

**Comment by BuckarooBanzay** [comment]
> Least complicated: ABM execution checks cable below or behind it (based on allowed connections) and reads network id from there. I think this should work without problems but it would have to also check if connected cable still belongs to network (cheap and easy check).

This sounds like the go-to solution i guess :+1: 

btw: I'm doing a `technic` + `jumpdrive` session when i'm in the "mood" for it again and like to address the network-moving and ABM to nodetimer issue

**Comment by S-S-X** [comment]
> This sounds like the go-to solution i guess 

Actually, already did that and tested a bit on local. I think I'm gonna push that stuff into switching branch and try to fix other problems. I think I have some time for that this weekend.
If not then changes can ofc be cherry picked if it is good enough.

`technic.networks[*].all_nodes` is no more indexed array, I believe this does not really matter unless network is really huge. Then it might have some performance impact in clear_networks function, well it happens that I also opened another ticket for that dept #95 :smile: 
Changed it to allow fast reverse lookup to check if position belongs to network cache == position is active in network and not detached indirectly (like cutting cables elsewhere).

**Comment by S-S-X** [comment]
So also tested "disconnected" power monitor a bit, not much but basic stuff:

:heavy_check_mark: Power monitor displays correct values for supply and demand in simple network.
:heavy_check_mark: Power monitor displays "no network" when cable below is removed.
:heavy_check_mark: Power monitor displays "no network" when cable is cut elsewhere between switch and power monitor.
:heavy_check_mark: Power monitor displays correct values after cable is restored, for both cases above.
:heavy_check_mark: Power monitor only works if cable is connected behind or below, otherwise displays "no network".
:heavy_check_mark: Power monitor displays "no network" if switching station is removed.
:heavy_check_mark: Power monitor resumes normal operation after switching station is restored.

Power monitor has priority for connection and does not create network conflict if connected to 2 different power networks, instead it prefers connection from below and only checks connection from behind if there's no active cable below it.
